name = "install-passportui"
compatibility_date = "2024-01-15"

[env.production]
name = "install-passportui"

[[env.production.routes]]
pattern = "install.passportui.com/*"
zone_name = "passportui.com"
