name: 📚 Documentation Issue
description: Report an issue with documentation or request documentation improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear documentation is essential for a great developer experience.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to make sure this hasn't been reported yet
          required: true
        - label: I have checked the latest documentation
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - README
        - Component Documentation
        - API Reference
        - Installation Guide
        - Usage Examples
        - Storybook Stories
        - TypeScript Definitions
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing Documentation
        - Incorrect Information
        - Unclear Instructions
        - Outdated Content
        - Broken Links
        - Typos/Grammar
        - Missing Examples
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation issue located?
      placeholder: e.g., README.md, src/components/button.tsx, Storybook story
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? (copy/paste the relevant section)
      render: markdown

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the problem with the current documentation
      placeholder: What's wrong, missing, or unclear about the current documentation?
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should this be improved?
      placeholder: What changes would make this documentation better?
    validations:
      required: true

  - type: textarea
    id: proposed-content
    attributes:
      label: Proposed Content
      description: If you have specific content suggestions, please provide them here
      render: markdown

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context that might be helpful

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in helping fix this documentation issue?
      options:
        - label: I would be interested in submitting a PR to fix this
        - label: I would prefer someone else handles this
